# Generated by Django 2.2 on 2021-11-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
