# Generated by Django 2.2 on 2021-11-23 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211123_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cancellation_reason', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_salon_cancellation_reasons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-added_date',),
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100)),
                ('business_phone_number', models.CharField(max_length=15)),
                ('business_email', models.EmailField(max_length=254)),
                ('price_range', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salons_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SalonCustomer',
            fields=[
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('bio_description', models.CharField(blank=True, max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NM', 'Non Binary')], default='Male', help_text='Select gender', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_customers', to=settings.AUTH_USER_MODEL)),
                ('salon_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_salon', to='main_app.Salon')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SalonOnsiteBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('service_date', models.DateTimeField()),
                ('service_started', models.BooleanField(default=False)),
                ('service_completed', models.BooleanField(default=False)),
                ('service_cancelled', models.BooleanField(default=False)),
                ('multiple_stylists_assigned', models.BooleanField(default=False)),
                ('negotiate_service_price', models.BooleanField(default=False)),
                ('negoriated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('booked_in_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='SalonOperationDays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=15)),
                ('start_time', models.TimeField()),
                ('end_stime', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('linked_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_operation_days', to='main_app.Salon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_operation_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SalonService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_duration', models.DurationField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('linked_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salon_services', to='main_app.Salon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_salon_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('category_description', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SalonStylist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_salon_stylists', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salon_stylists', to='main_app.Salon')),
                ('salon_services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_stylists', to='main_app.SalonService')),
                ('working_days', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stylists_assigned', to='main_app.SalonOperationDays')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='salonservice',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_services', to='main_app.ServiceCategory'),
        ),
        migrations.CreateModel(
            name='SalonOnsiteBookingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_option', models.CharField(choices=[('C', 'Cash'), ('M', 'Mobile'), ('CD', 'Card')], max_length=2)),
                ('payment_code', models.CharField(blank=True, max_length=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_for', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main_app.SalonOnsiteBooking')),
                ('payment_received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_payments', to='main_app.Salon')),
            ],
            options={
                'ordering': ('-payment_date',),
            },
        ),
        migrations.AddField(
            model_name='salononsitebooking',
            name='booked_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_bookings', to='main_app.SalonService'),
        ),
        migrations.AddField(
            model_name='salononsitebooking',
            name='cancellation_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_reasons_bookings', to='main_app.CancellationReason'),
        ),
        migrations.AddField(
            model_name='salononsitebooking',
            name='salon_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_bookings', to='main_app.SalonCustomer'),
        ),
        migrations.AddField(
            model_name='salononsitebooking',
            name='stylists',
            field=models.ManyToManyField(to='main_app.SalonStylist'),
        ),
    ]
