# Generated by Django 2.2 on 2022-05-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211123_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salononsitebooking',
            old_name='negoriated_price',
            new_name='negotiated_price',
        ),
    ]
