#%RAML 1.0
title: Salon API
version: 1
baseUri: http://localhost:8000/api/{version}
mediaType: application/json

uses:
  shapes: ./dataTypes/shapes.raml

traits:
  contentCacheable: !include ./traits/content-cacheable.raml
  secured: !include ./traits/secured.raml
  pageable: !include  ./traits/pageable.raml

resourceTypes:
  collection: !include ./resourceTypes/collection.raml
  booking: !include ./resourceTypes/booking.raml
  salon: !include ./resourceTypes/salon.raml
  customer: !include ./resourceTypes/customer.raml
  stylist: !include ./resourceTypes/salon.raml
  service_category: !include ./resourceTypes/service-category.raml
  service: !include ./resourceTypes/services.raml

securedBy: [oauth_2_0]
securitySchemes:
  oauth_2_0: !include ./securitySchemes/oauth_2_0.raml

/salons:
  type:  { collection: {response-type : shapes.SalonData[], request-type : shapes.NewSalonRequestData } }
  get:
    is: [pageable]
    responses:
      200:
        body:
          application/json:
            example:|
              {
                "salons": [
                {
                  "id": "6ddfty-078rty-8986533gh",
                  "business_name": "Salon Star"
                },
                {
                  "id": "4567-dfgty-4456789ft",
                  "business_name": "Happy Paradise"
                }
                {
                  "id": "t678-3456-6789hgyt",
                  "business_name": "Women Heaven"
                }
                ]
              }

  post:
    is: [secured]
    description: |
      salon data created correctly for a salon
    queryParameters:
      access_token: string
      business_name: string
      business_type: string
      business_description: string
      business_phone_number: string
      business_email: string
    body:
      type: shapes.NewSalonRequestData
    responses:
      200:
        body:
          application/json:
            example: |
              {"message": " New Salon created successfully!"}

  /{salon_id}:
    type:
       {
       salon:
         {
         get-response-type : shapes.SalonData,
         get-response-example :
           id: "uuid-4567-hgyt78-345fgtyr"
           owner:
             id: "uuid-4567-ghyt-2345tyu"
             email: "taruki@salonstar.com"
             phone_number: "076785678"
             user_type: "is_serviceprovider"
             nationality: "Japanese"
             city: "Tokyo"
           business_name: "Salon Star"
           business_type: "Hair Salon"
           business_description: "Hair haven"
           business_phone_number: "0786456456"
           business_email: "hello@salonstar.com"
           business_address:
             address_country: "Japan"
             address_city: "Tokyo"
             address_region: "Kanto"
             postal_code: "184-00003"
             address_street: "2-34-45 Chuo-ku"
             longitude: "139.4567"
             latitude: "35.672"
          ,
         patch-response-type : shapes.SalonPatchData
          }
        }
      uriParameters:
        salon_id: string

    delete:
      description: Delete a salon by id
      responses:
        204:
        404:
          body:
            application/json:
              type: shapes.Error
              example: {"error_message": "Not found"}

/salon-services-categories:
  type: { collection: {response-type : shapes.SalonServicesCategoryData[], request-type : shapes.NewSalonServiceCategoryData}}
  is: [secured]
  get:
    is: [pageable]
    responses:
      200:
        body:
          application/json:
            example:|
              {
                "salons": [
                {
                  "id": "6ddfty-078rty-8986533gh",
                  "business_name": "Salon Star"
                },
                {
                  "id": "4567-dfgty-4456789ft",
                  "business_name": "Happy Paradise"
                }
                {
                  "id": "t678-3456-6789hgyt",
                  "business_name": "Women Heaven"
                }
                ]
              }

  post:
    description: salon services category created successfully
    body:
      application/json:
        type: shapes.NewSalonServiceCategoryData

  /{category_id}:
    type:
       {
       service_category:
         {
         get-response-type : shapes.SalonServiceCategoryData,
         get-response-example :
           id: "uuid-6756-rtyt78-345f67yr"
           owner:
             id: "uuid-4567-ghyt-2345tyu"
           category_name: "Hair"
           category_description: "Hair Services"
           created: "2021-10-09 8:00 A.M"
          ,
         patch-response-type : shapes.SalonServiceCategoryPathData
          }
        }
      uriParameters:
        category_id: string

    delete:
      description: Delete a salon service category by id
      responses:
        204:
        404:
          body:
            application/json:
              type: shapes.Error
              example: {"error_message": "Not found"}

/salon-services:
  type:  { collection: {response-type : shapes.SalonServicesData[], request-type : shapes.CreateUpdateSalonServiceData } }
    is: [secured]
      get:
        is: [pageable]
          responses:
            200:
              body:
                application/json:
                  example:|
                    {
                      "salons": [
                        {
                          "id": "6ddfty-0987645-yyrt6533gh",
                          "service_name": "Hair Treatment"
                        },
                        {
                          "id": "5677-dfgty-44ert89ft",
                          "service_name": "Hair Cut"
                        }
                        {
                          "id": "6768-3456-kh0yu56gyt",
                          "service_name": "Hair Coloring"
                        }
                        ]
                    }
      post:
        is: [secured]
        description: |
          salon service created successfully
        queryParameters:
          access_token: string
          service_category: shapes.SalonServiceCategoryData.id
          linked_business: shapes.SalonData.id
          service_price: number
          service_duration: string
        body:
          type: shapes.CreateUpdateSalonServiceData
        responses:
          200:
            body:
              application/json:
                example: |
                  {"message": " New Service created successfully!"}

  /{service_id}:
    type:
      {
        service:
          {
          get-response-type: shapes.SalonServicesData,
          get-response-example:
            id: "4567-ert5-tyu7645dfg89"
            owner:
              id: "uuid-4567-ghyt-2345tyu"
            service_name: "Hair Styling"
            service_category: "Hair Services"
            linked_business:
              id: "uuid-4567-hgyt78-345fgtyr"
              owner:
                id: "uuid-4567-ghyt-2345tyu"
              business_name: "Salon Star"
              business_type: "Hair Salon"
              business_description: "Hair haven"
              business_phone_number: "0786456456"
              business_email: "hello@salonstar.com"
              business_address:
                address_country: "Japan"
                address_city: "Tokyo"
                address_region: "Kanto"
                postal_code: "184-00003"
                address_street: "2-34-45 Chuo-ku"
                longitude: "139.4567"
                latitude: "35.672"
            service_price: "10,000"
            service_duration: "1 hour"
            ,
            patch-response-type: shapes.CreateUpdateSalonServiceData
          }

      }
    uriParameters:
      service_id: string
    delete:
      description: Delete a salon service by id
      responses:
        204:
        404:
          body:
            application/json:
              type: shapes.Error
              example: {"error_message": "Not found"}

/customers:
  type:  { collection: {response-type : shapes.SalonCustomerData[], request-type : shapes.SalonCustomerData } }
  is: [secured]
    get:
      is: [pageable]
        responses:
          200:
            body:
              application/json:
                example:|
                  {
                    "customers": [
                      {
                        "id": "ddf8y-0trtye5-yyrr5678h",
                        "first_name": "Terry",
                        "last_name": "Sato"
                      },
                      {
                      "id": "ttf8y-05645e5-yyxfty78h",
                      "first_name": "John",
                      "last_name": "Kisaki"
                      }
                      {
                      "id": "456t8y-456tyue5-yyr456tyh",
                      "first_name": "Kim",
                      "last_name": "Sato"
                      }
                      ]
                  }

    post:
      is: [secured]
        description: |
          salon customer created successfully
        queryParameters:
          access_token: string
          first_name: string
          last_name: string
          DOB: date-only
          home_address: string
          registered_by: shapes.UserData.id
          salon_branch: shapes.SalonData.id
        body:
          type: shapes.SalonCustomerData
            responses:
              200:
                body:
                  application/json:
                    example: |
                      {"message": " New customer created successfully!"}

  /{salon_id}/{customer_id}:
    type:
      {
        customer:
          {
          get-response-type: shapes.SalonCustomerData,
          get-response-example:
            id: "456t8y-456tyue5-yyr456tyh"
            registered_by:
              id: "uuid-4567-ghyt-2345tyu"
            first_name: "Kim"
            last_name: "Sato"
            linked_business:
              id: "uuid-4567-hgyt78-345fgtyr"
              owner:
                id: "uuid-4567-ghyt-2345tyu"
              business_name: "Salon Star"
              business_type: "Hair Salon"
              business_description: "Hair haven"
              business_phone_number: "0786456456"
              business_email: "hello@salonstar.com"
              business_address:
                address_country: "Japan"
                address_city: "Tokyo"
                address_region: "Kanto"
                postal_code: "184-00003"
                address_street: "2-34-45 Chuo-ku"
                longitude: "139.4567"
                latitude: "35.672"
            gender: "Male"
            DOB: "2000-10-09"
            home_address: "2-34-5 Chuo Ku"
            created: "2021-10-18 09:00 A.M"
            ,
            patch-response-type: shapes.UpdateSalonServiceData
          }

      }
    uriParameters:
      salon_id: string
      customer_id: string

    delete:
      description: Delete a salon customer by id
      responses:
        204:
        404:
          body:
            application/json:
              type: shapes.Error
              example: {"error_message": "Not found"}


/bookings:
  type:  { collection: {response-type : shapes.SalonOnsiteBookingsData[], request-type : shapes.SalonOnsiteBookingsData } }
  is: [secured]
    get:
      is: [pageable]
        responses:
          200:
            body:
              application/json:
                example:|
                  {
                    "bookings": [
                      {
                        "id": "ttyu0-45676-yyr9878h",
                        "salon_customer": "Terry",
                        "booked_service": "Hair Cut"
                      },
                      {
                      "id": "88tyy-0564r-5567ty78h",
                      "salon_customer": "John",
                      "booked_service": "Hair coloring"
                      }
                      {
                      "id": "6788y-4678e5-yvfgty89h",
                      "salon_customer": "Kim",
                      "booked_service": "Hair treatment"
                      }
                      ]
                  }

    post:
      is: [secured]
        description: |
          salon booking created successfully
        queryParameters:
          access_token: string
          salon_customer: shapes.SalonCustomerData.id
          booked_in_by: shapes.UserData.id
          stylists: shapes.SalonStylistData.id
          booked_service: shapes.SalonServicesData.id
          booking_creation_date: datetime
          service_date: datetime
        body:
          type: shapes.SalonOnsiteBookingsData
            responses:
              200:
                body:
                  application/json:
                    example: |
                      {"message": " New booking created successfully!"}

  /{salon_id}/{booking_id}:
    type:
      {
        booking:
          {
          get-response-type: shapes.SalonOnsiteBookingsData,
          get-response-example:
            id: "77t8y-45666ue5-yyr45yh"
            salon_customer:
              id: "ttyu0-45676-yyr9878h"
            booked_service: "hair Cut"
            booking_creation_date: "2021-10-04 08:00 A.M"
            service_date: "2021-10-08 12:30 P.M"
            service_started: false
            service_completed: false
            service_cancelled: false
            cancellation_reason: SalonServiceCancellationReasonData
            multiple_stylists_assigned: false
            negotiate_service_price: false
            negotiated_price: "0.00"
            stylists[]:
              {
               "stylists": [
               {
                  "id": "uuid-555-g778-2345tyu"
                }
              ]
            }
            ,
            patch-response-type: shapes.UpdateSalonOnsiteBookingsData
          }

      }
    uriParameters:
      salon_id: string
      booking_id: string

    delete:
      description: Delete a salon booking by id
      responses:
        204:
        404:
          body:
            application/json:
              type: shapes.Error
              example: {"error_message": "Not found"}


/stylists:
  type:  { collection: {response-type : shapes.SalonStylistData[], request-type : shapes.SalonStylistData } }
  is: [secured]
    get:
      is: [pageable]
        responses:
          200:
            body:
              application/json:
                example:|
                  {
                    "stylists": [
                      {
                        "id": "zx6yu0-45676-yyr9878h",
                        "first_name": "Jenji",
                        "last_name": "Kohan"
                      },
                      {
                      "id": "8856y-fgrt4r-5567t4378h",
                      "first_name": "John",
                      "last_name": "Hair coloring"
                      }
                      {
                      "id": "747rt-4785e5-345yty67h",
                      "first_name": "Kim",
                      "last_name": "Loius"
                      }
                      ]
                  }

    post:
      is: [secured]
        description: |
          Create a salon stylist
        queryParameters:
          access_token: string
          owner: shapes.UserData.id
          first_name: string
          last_name: string
          phone_number: string
          email: string
          salon_branch: shapes.SalonData.id
        body:
          type: shapes.SalonStylistData
            responses:
              200:
                body:
                  application/json:
                    example: |
                      {"message": " New stylis created successfully!"}

  /{salon_id}/{stylist_id}:
    type:
      {
        stylist:
          {
          get-response-type: shapes.SalonStylistData,
          get-response-example:
            id: "77t8y-45666ue5-yyr45yh"
            owner:
              id: "ttyu0-45676-yyr9878h"
            first_name: "Kim"
            last_name: "Louis"
            phone_number: "080456897"
            email: "kim@salonstar.com"
            salon_branch: "Salon Star"
            working_days[]:
              {
                "days": [
                {
                  "id": "xsdft-67854",
                  "day": "Monday"
                },
                {
                  "id": "zxrt67t-678e54",
                  "day": "Tuesday"
                },
                {
                  "id": "xsdft-674rty4",
                  "day": "Wednesday"
                },
                {
                  "id": "vxerft-34rty54",
                  "day": "Thursday"
                }
                ]
              }
            date_joined: "2021-10-10"
            salon_services[]:
              {
               "services": [
               {
                  "id": "uuid-456-ggh78-2344yu",
                  "service_name": "Hair Cut"
                }
              ]
            }
            ,
            patch-response-type: shapes.UpdateSalonOnsiteBookingsData
          }

      }
    uriParameters:
      salon_id: string
      stylist_id: string

    delete:
      description: Delete a salon stylist booking by id
      responses:
        204:
        404:
          body:
            application/json:
              type: shapes.Error
              example: {"error_message": "Not found"}
