#%RAML 1.0
title: songs API
baseUri: http://api.songs.com/{version}
version: v1

/songs:
  get:
    description: get list of songs based on title
    queryParameters:
      songTitle:
        description: "The title of song to search"
        required: true
        minLength: 3
        type: string
        example: "Get L"
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "songs": [
                  {
                    "songId": "33345637-3345678-2345",
                    "songTitle": "get Lucky"
                  },
                  {
                    "songId": "550e8400-e29b-41d4-q716-4466452345",
                    "songTitle": "Loose yourself to dance"
                  }
                ]
              }
  post:
  /{songId}:
    description: get the song with `songId = {songId}`
    get:
      description: Get the song with `songId = {songId}`
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "songId": "550e8400-e29b-41d4-789456",
                  "songTitle": "Get Lucky",
                  "duration": "6:07"
                }
      /file-content:
        get:
        post:
/artists:
  get:
  post:
  /{artistId}:
    get:
    /albums:
      get:
/albums:
  get:
  post:
  /{albumId}:
    get:
    /songs:
      get:
