#%RAML 1.0
usage: Applied to any Salon API method that require object level access control
description: Some Salon API methods require enforcing object level access control to prevent BOLA vulnerability
