#%RAML 1.0

usage: Applied to any Salon API method that needs to be secured
description: Some Salon API requests require authentication
headers:
  access_token:
    description: request access token
    example: 34rt567yghrty678345dfer3
    type: string
    required: true
