#%RAML 1.0 Library

usage: Common traits for Salon API

traits:
  partial: !include partial.raml
  pageable: !include pageable.raml
  contentCacheable: !include content-cacheable.raml
  secured: !include secured.raml
