#%RAML 1.0 ResourceType

usage: Resource type applied to a service-category resource that returns only a single item.

uses:
 traits: ../traits/traits.raml

get:
  is: [ traits.partial ]
  description: Returns <<resourcePathName | !singularize>> data
  responses:
    200:
      body:
        application/json:
          type: <<get-response-type>>
          example: <<get-response-example>>
    404:
      body:
        application/json:
          example: |
            {"message": "resourcePathName| !singularize>> not found"}
patch?:
  description: Updates <<resourcePathName | !singularize>> data
  responses:
    200:
      body:
        application/json:
          type: <<patch-response-type>>
delete?:
  description: Removes a <<resourcePathName | !singularize>> from the system
